spring:
  application:
    name: listing-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}
      database: artisan_listings

server:
  port: ${PORT:8081}

integration:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8080}
  review-service:
    url: ${REVIEW_SERVICE_URL:http://localhost:8083}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
