spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}
      database: artisan_orders

server:
  port: ${PORT:8082}

integration:
  api-gateway:
    url: ${API_GATEWAY_URL:http://localhost:8084}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
